### PR TITLE
FOSSGIS logo position

### PR DESCRIPTION
**Pull request by pathmapper**
**Before:**
image

**This PR:**
image

### CODE REVIEW

**Comment by joto** [comment]
On my screen the former looked okay with a line break after the "by". I have changed the size of the box to be relative to the text width, can you check whether this looks okay on your browser now?

**Comment by pathmapper** [comment]
Thanks, with https://github.com/fossgis/osmdata/commit/bda428f62536be6d3ecc747fcb71cecdad63670b it looks okay now (Firefox and Chrome on Debian).

**Comment by pathmapper** [comment]
@joto the fix is not available on https://osmdata.openstreetmap.de/. Do you need to push it to the server?

**Comment by joto** [comment]
Fixed.

**Pull request closed without merging**
